# Generated by Django 4.2.4 on 2023-08-31 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_uploadedcsvfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companiesmodel',
            old_name='name',
            new_name='company_name',
        ),
    ]
